import SOPActivity from '@/models/SOPActivity';
import connectDB from '@/lib/mongodb';

/**
 * Activity Logger - Centralized logging for all SOP activities
 * Captures precise timestamps and detailed user actions
 */

export interface LogActivityParams {
  // SOP Information
  sopId: string;
  sopIdentifier: string;
  sopName: string;
  
  // User Information
  userId: string;
  userName: string;
  userRole: string;
  userDepartment?: string;
  
  // Action Details
  actionType: 'created' | 'updated' | 'reviewed' | 'approved' | 'rejected' | 'downloaded' | 'viewed' | 'expired' | 'deleted' | 'restored' | 'merged';
  actionCategory: 'lifecycle' | 'content' | 'access' | 'compliance' | 'administrative';
  
  // Change Tracking (for updates)
  fieldsChanged?: string[];
  previousValues?: Record<string, any>;
  updatedValues?: Record<string, any>;
  
  // Context
  reason?: string;
  comments?: string;
  
  // Metadata
  ipAddress?: string;
  userAgent?: string;
  sessionId?: string;
  
  // System
  systemGenerated?: boolean;
  requiresApproval?: boolean;
}

/**
 * Log an SOP activity with full timestamp and user tracking
 */
export async function logSOPActivity(params: LogActivityParams) {
  try {
    await connectDB();
    
    const activity = await SOPActivity.create({
      // Core Identifiers
      sopId: params.sopId,
      sopIdentifier: params.sopIdentifier,
      sopName: params.sopName,
      
      // User Information
      userId: params.userId,
      userName: params.userName,
      userRole: params.userRole,
      userDepartment: params.userDepartment,
      
      // Action Details
      actionType: params.actionType,
      actionCategory: params.actionCategory,
      
      // Timestamp (auto-generated by MongoDB)
      timestamp: new Date(),
      
      // Change Tracking
      fieldsChanged: params.fieldsChanged,
      previousValues: params.previousValues,
      updatedValues: params.updatedValues,
      
      // Context
      reason: params.reason,
      comments: params.comments,
      
      // Metadata
      ipAddress: params.ipAddress,
      userAgent: params.userAgent,
      sessionId: params.sessionId,
      
      // System
      systemGenerated: params.systemGenerated || false,
      requiresApproval: params.requiresApproval || false,
    });
    
    return {
      success: true,
      activityId: activity._id.toString(),
      timestamp: activity.timestamp,
    };
  } catch (error: any) {
    console.error('Error logging SOP activity:', error);
    return {
      success: false,
      error: error.message,
    };
  }
}

/**
 * Get activity timeline for a specific SOP
 */
export async function getSOPActivityTimeline(sopId: string, limit: number = 50) {
  try {
    await connectDB();
    
    const activities = await SOPActivity.find({ sopId })
      .sort({ timestamp: -1 })
      .limit(limit)
      .lean();
    
    return {
      success: true,
      activities,
      total: activities.length,
    };
  } catch (error: any) {
    console.error('Error fetching SOP activity timeline:', error);
    return {
      success: false,
      error: error.message,
      activities: [],
    };
  }
}

/**
 * Get user activity history
 */
export async function getUserActivityHistory(userId: string, limit: number = 100) {
  try {
    await connectDB();
    
    const activities = await SOPActivity.find({ userId })
      .sort({ timestamp: -1 })
      .limit(limit)
      .lean();
    
    return {
      success: true,
      activities,
      total: activities.length,
    };
  } catch (error: any) {
    console.error('Error fetching user activity history:', error);
    return {
      success: false,
      error: error.message,
      activities: [],
    };
  }
}

/**
 * Get activities by date range
 */
export async function getActivitiesByDateRange(
  startDate: Date,
  endDate: Date,
  filters?: {
    actionType?: string;
    userId?: string;
    department?: string;
    sopId?: string;
  }
) {
  try {
    await connectDB();
    
    const query: any = {
      timestamp: {
        $gte: startDate,
        $lte: endDate,
      },
    };
    
    if (filters?.actionType) query.actionType = filters.actionType;
    if (filters?.userId) query.userId = filters.userId;
    if (filters?.department) query.userDepartment = filters.department;
    if (filters?.sopId) query.sopId = filters.sopId;
    
    const activities = await SOPActivity.find(query)
      .sort({ timestamp: -1 })
      .lean();
    
    return {
      success: true,
      activities,
      total: activities.length,
      dateRange: { startDate, endDate },
    };
  } catch (error: any) {
    console.error('Error fetching activities by date range:', error);
    return {
      success: false,
      error: error.message,
      activities: [],
    };
  }
}

/**
 * Get activity statistics
 */
export async function getActivityStatistics(filters?: {
  startDate?: Date;
  endDate?: Date;
  department?: string;
}) {
  try {
    await connectDB();
    
    const query: any = {};
    
    if (filters?.startDate && filters?.endDate) {
      query.timestamp = {
        $gte: filters.startDate,
        $lte: filters.endDate,
      };
    }
    
    if (filters?.department) {
      query.userDepartment = filters.department;
    }
    
    // Aggregate statistics
    const stats = await SOPActivity.aggregate([
      { $match: query },
      {
        $group: {
          _id: null,
          totalActivities: { $sum: 1 },
          uniqueUsers: { $addToSet: '$userId' },
          uniqueSOPs: { $addToSet: '$sopId' },
          actionTypes: { $push: '$actionType' },
        },
      },
    ]);
    
    // Count by action type
    const actionTypeCounts = await SOPActivity.aggregate([
      { $match: query },
      {
        $group: {
          _id: '$actionType',
          count: { $sum: 1 },
        },
      },
    ]);
    
    // Most active users
    const topUsers = await SOPActivity.aggregate([
      { $match: query },
      {
        $group: {
          _id: { userId: '$userId', userName: '$userName' },
          activityCount: { $sum: 1 },
        },
      },
      { $sort: { activityCount: -1 } },
      { $limit: 10 },
    ]);
    
    return {
      success: true,
      statistics: {
        totalActivities: stats[0]?.totalActivities || 0,
        uniqueUsers: stats[0]?.uniqueUsers?.length || 0,
        uniqueSOPs: stats[0]?.uniqueSOPs?.length || 0,
        actionTypeCounts,
        topUsers,
      },
    };
  } catch (error: any) {
    console.error('Error fetching activity statistics:', error);
    return {
      success: false,
      error: error.message,
    };
  }
}

/**
 * Get recent activities (last 24 hours)
 */
export async function getRecentActivities(hours: number = 24, limit: number = 50) {
  const startDate = new Date();
  startDate.setHours(startDate.getHours() - hours);
  
  return getActivitiesByDateRange(startDate, new Date());
}

/**
 * Compare SOP versions (track what changed)
 */
export function compareSOPVersions(previous: any, updated: any): {
  fieldsChanged: string[];
  previousValues: Record<string, any>;
  updatedValues: Record<string, any>;
} {
  const fieldsChanged: string[] = [];
  const previousValues: Record<string, any> = {};
  const updatedValues: Record<string, any> = {};
  
  // Fields to track
  const trackedFields = [
    'name', 'identifier', 'department', 'owner', 'version',
    'reviewDate', 'expiryDate', 'effectiveDate', 'processArea',
    'guidelineReference', 'remarks', 'status'
  ];
  
  for (const field of trackedFields) {
    if (previous[field] !== updated[field]) {
      fieldsChanged.push(field);
      previousValues[field] = previous[field];
      updatedValues[field] = updated[field];
    }
  }
  
  return { fieldsChanged, previousValues, updatedValues };
}
